### ISSUE TITLE
Encode request data as JSON when Content-Type is set to application/json

### ISSUE THREAD

**Issue by jonkoops** [ded/reqwest#118]
When the the `Content-Type` header of a request is set to `application/json` shouldn't the request data be converted to a JSON string using `JSON.stringify`?

Currently I'm sending my requests like this:

``` js
reqwest({
    url: '/api/v1/user',
    type: 'json',
    method: 'post',
    contentType: 'application/json',
    processData: false,
    data: JSON.stringify({
        first_name: 'John',
        last_name: 'Doe'
    })
});
```

But it would be easier if I could do this:

``` js
reqwest({
    url: '/api/v1/user',
    type: 'json',
    method: 'post',
    contentType: 'application/json',
    data: {
        first_name: 'John',
        last_name: 'Doe'
    }
});
```

**Comment by ruifortes** [comment]
Same here +1

**Comment by Huxpro** [comment]
+1

**Comment by jonkoops** [comment]
I'd recommend using the new [Fetch API](https://fetch.spec.whatwg.org/), it does the same as request but it has a nice Promise based API. It's not in browsers yet but there are [polyfills available](https://github.com/github/fetch).

**Comment by Huxpro** [comment]
@jonkoops fully agree

**Comment by danhardman** [comment]
+1 Just started using reqwest and encountered this. Definitely would be a great addition.

**Comment by torarnek** [comment]
+1

**Comment by mrconnormurphy** [comment]
+1

**Comment by danhardman** [comment]
Opened a pull request #238
