### ISSUE TITLE
Make reqwest client/server agnostic

### ISSUE THREAD

**Issue by appsforartists** [ded/reqwest#153]
Right now, trying to use reqwest from Node results in this error:

    > var reqwest = require("reqwest")
    ReferenceError: window is not defined
        at ./node_modules/reqwest/reqwest.js:13:13
        at win (./node_modules/reqwest/reqwest.js:8:72)
        at Object.<anonymous> (./node_modules/reqwest/reqwest.js:11:2)
        at Module._compile (module.js:449:26)
        at Object.Module._extensions..js (module.js:467:10)
        at Module.load (module.js:349:32)
        at Function.Module._load (module.js:305:12)
        at Module.require (module.js:357:17)
        at require (module.js:373:17)
        at repl:1:15

Given that there are [projects to provide the XHR interface in Node](https://github.com/driverdan/node-XMLHttpRequest), making reqwest isomorphic should be as simple as abstracting out the implicit use of globals like `window` and `document`.

**Comment by blainekasten** [comment]
+1 for agnosticism. (in this context)

**Comment by raysuelzer** [comment]
+1  right now, I can't use the library with reactjs,net without a hassle.

**Comment by raysuelzer** [comment]
@appsforartists  could you put in a pull request for this issue?  Isomorphic apps are becoming more and more popular, so being able to include this dependency in webpack is pretty important.  I don't want to have to hack together two different versions of my javascript more than I need to.

**Comment by appsforartists** [comment]
@raysuelzer sure.  FWIW, I use [mach](https://github.com/mjackson/mach/) now, which is agnostic.  If you're feeling future-proof, there's also [fetch](https://github.com/matthew-andrews/isomorphic-fetch).

**Comment by appsforartists** [comment]
@raysuelzer I don't know if @ded is interested, but there's now a PR open at #185.

**Comment by blainekasten** [comment]
@appsforartists thanks for doing that! Hopefully @ded is interested.

**Comment by luandro** [comment]
+1 for reqwest in isomorphic apps

**Comment by yicone** [comment]
+1 for reqwest in isomorphic apps

**Comment by iamrandys** [comment]
+1

**Comment by ded** [comment]
alright this is officially on the radar. i'll have a look at that open PR as well!

**Comment by ded** [comment]
@appsforartists @blainekasten @raysuelzer @luandro @yicone 

Thanks tons for being patient on this! Given the high level of interest on this, and taking into account the history of this project, we'll have to consider a solution that continues to support the original purpose (the browser) and somehow add a peer dependency for Node.js (like the `xhr2` library) that doesn't conflict with other client package managers (like Browserify, RequireJS, or Ender).

In the meantime, I'll try and have a play with a solution
