### ISSUE TITLE
Borks on an HTTP 204 response

### ISSUE THREAD

**Issue by jalada** [ded/reqwest#160]
If the server sends a 204 status code, Reqwest raises an exception:

```
reqwest("/204") // https://gist.github.com/jalada/fda3dc2d14d05efe97ba

Uncaught TypeError: Cannot read property 'match' of null  reqwest.js:239
  setType                                                 reqwest.js:239
  success                                                 reqwest.js:300
  (anonymous function)                                    reqwest.js:85
```

**Comment by rosko** [comment]
I got the same error. It happens when response contains no "Content-Type" AND request options has no "type" option.
I've just added "type" into request options. And it works.

**Comment by okonet** [comment]
+1

**Comment by ded** [comment]
ok it looks like the PR for the fix it obviously out of date. we should try and get this fix in

**Comment by odzb** [comment]
**ded**, can you please publish the fixed code on **npm** as 2.0.2? Thank you very much for your work, we depend on it a lot :)

**Comment by ded** [comment]
yikes i forgot to publish

**Comment by ded** [comment]
done!

**Comment by odzb** [comment]
Thank you! One step further would be to put this fix into 1.x (the non-xhr2 version stream) as well.
