### ISSUE TITLE
not handling undefined data in querystring

### ISSUE THREAD

**Issue by jiyinyiyong** [ded/reqwest#187]
It was supposed to be dropped. I remmembered jQuery drops such properties..(I have to confirm this..)

```js
>  data = {a: undefined, b: 1}
<- Object {a: undefined, b: 1}
>  reqwest.toQueryString(data)
<- "a=&b=1
```

expected: `b=1`
https://github.com/ded/reqwest/blob/master/src/reqwest.js#L473

**Comment by ded** [comment]
regardless, a is still undefined. is this causing bugs in your code?

**Comment by jiyinyiyong** [comment]
Found jQuery doing this. Mymistake.
```js
jQuery.param({a:1, b: undefined, c: null, d:''})
"a=1&b=&c=&d="
```

It did cause problems on my side. `""` and `undefined` can not be told. Well at least not a problem of Reqwest.
