### ISSUE TITLE
Is is possible to reject a request while in `then`?

### ISSUE THREAD

**Issue by norbertpy** [ded/reqwest#193]
In `then` function of my request I'm getting some data and if `data.flag === false`, the request should not fulfill (get failed). How can I do that? 

By the way, `reqwest` is awesome.

**Comment by ded** [comment]
i've been avoiding promise based bugs until we can get a "real" working promise lib integrated into it

**Comment by norbertpy** [comment]
@ded, thanks. So How do I do it in `success` (non-promise version)?

**Comment by ded** [comment]
are you trying to handle a failure case in the success handler?

``` js
function fail() {
  // do stuff...
}

ajax({
  url: '/api',
  method: 'post',
  error: fail,
  success: function (data) {
    if (data.flag === false) return fail()
   // otherwise do successful stuff...
  }  
})
```

**Comment by norbertpy** [comment]
Thank you very much.
