### ISSUE TITLE
hasOwnProperty fails in IE9

### ISSUE THREAD

**Issue by OliverJAsh** [ded/reqwest#202]
https://github.com/ded/reqwest/commit/6942e2d58f0442a509b0ed986de5f76e932aa803#diff-fb0db1c9acd7433e9cca0719798217f7R15

**Comment by ded** [comment]
Perhaps `"window" in context` will work best then.

**Comment by kristoffernolgren** [comment]
this is also a stopping fail in ie11. https://jsfiddle.net/38yq14ro/2/

**Comment by kristoffernolgren** [comment]
(downgrading)
