### ISSUE TITLE
Using reqwest with browserify

### ISSUE THREAD

**Issue by glena** [ded/reqwest#205]
Hi,

I installed reqwest with npm and I am building my assets with browserify and when I require reqwest it try to require xhr2 because it asumes it runs on node .

Is there any workaround? (right now I am targeting to "^1.1.4" to make it work).

Thanks

**Comment by ded** [comment]
ok this is becoming a real issue. I will prioritize this

**Comment by ded** [comment]
this is related to #204

**Comment by ded** [comment]
@glena as you wait for a fix — you can temporarily add `xhr2` as a dependency to your main app and that will resolve the issue.

**Comment by puzzfuzz** [comment]
+1. 
I ran into this as well. Browserify fails and tosses an error into the logs for it. `npm install --save xhr2` made it happy again. Should probably note this in the README.md (or put any install steps in there in general).

**Comment by ded** [comment]
it's noted in the intro paragraph

`It is also isomorphic allowing you to require('reqwest') in Node.js through the peer dependency xhr2`

As a suplementary, I will add `npm install --save xhr2`

**Comment by puzzfuzz** [comment]
Not to split hairs, but as it stands now, it is required in the **browser** as well as Node.js. The note specifies Node.js, which is what threw me off :)

**Comment by ded** [comment]
yeah, that's the main issue right now and we need to sort out a workaround that works nicely with existing installations — or simply propose a different (breaking) solution with a minor version bump

**Comment by odzb** [comment]
Just have the node users do something like require('reqwest').xhr(require('xhr2')), while browser users (the majority, I presume) will continue to use require('reqwest'). The xhr2 dependency (amplified by the fact that it's even a normal dependency, it behaves like a bug unless you add xhr2 manually) is a major deal-breaker for reqwest :(

**Comment by ded** [comment]
the initial idea was that it "just worked" as-is, thus node vs browser wouldn't have to change their implementations.... which is still going to require some thought.
