### ISSUE TITLE
Please consider some lint work

### ISSUE THREAD

**Issue by robvon** [ded/reqwest#206]
Love the library - my editor is full of red ink reading it though:

- variables used outside block where defined.
- variables that redefine existing variables.
- I can understand your aversion to semi-colons but my editor is fussier.
- funcs that don't return values on all paths. This one makes you think a little.

For instance, just shifting the defn of "XHR2" could get rid of a whole heap of warnings

Nothing too tragic but it is a lot of boring warnings....

**Comment by ded** [comment]
There is a lint file that the project is being linted upon https://github.com/ded/reqwest/blob/master/.jshintrc

It all passes. If this is bothersome, disable your linter, or import the settings from the linked file. Hope this helps!

**Comment by robvon** [comment]
Yes I will look into that. Perhaps you could consider some of the stuff I  mentioned though...

R :-)

**Comment by ded** [comment]
yep i gotcha. i can fix a few of those. especially 2 & 4. Those are remnants of an earlier code style I used from years ago.
