### ISSUE TITLE
Errors: can't resolve in webpack

### ISSUE THREAD

**Issue by budarin** [ded/reqwest#209]
if you include package to project which builds webpach - you will see a lot of beautiful red errors listed in webpacks log and module isn't resolved :) - so it can't be used.

**Comment by chrtze** [comment]
I have the same problem, you can try downgrading to reqwest@1.1.6.

**Comment by budarin** [comment]
07.09.2015 19:32, Christopher пишет:
>
> I have the same problem, you can try downgrading to reqwest@1.1.6.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ded/reqwest/issues/209#issuecomment-138336113>.
>
thanks!

**Comment by afc163** [comment]
Fork a http://npmjs.com/reqwest-without-xhr2 for this.

**Comment by limi58** [comment]
reqwest@2.0.1 can work

**Comment by budarin** [comment]
Thanks!I use rewqest-without-xhr2 it hasn't the problem and hasn't dependency on xhr2 component12:49, 13 сентября 2015 г., limi58 <notifications@github.com>:reqwest@2.0.1 can work —Reply to this email directly or view it on GitHub.     С уважением Бударин Вадим
